# Generated by Django 4.2.9 on 2024-01-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='categories.subgroup', verbose_name='Подгруппа')),
            ],
        ),
    ]
