# Generated by Django 4.2.9 on 2024-01-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('scope_of_application', models.CharField(max_length=200, verbose_name='Сфера применения')),
                ('diametr', models.FloatField(verbose_name='Диаметр')),
                ('length', models.FloatField(verbose_name='Длинна')),
                ('image', models.ImageField(default='', null=True, upload_to='', verbose_name='Изображение')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.card', verbose_name='карточка')),
            ],
        ),
    ]
