# Generated by Django 4.2.9 on 2024-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diametr',
            field=models.IntegerField(verbose_name='Диаметр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.IntegerField(verbose_name='Длинна'),
        ),
    ]
