# Generated by Django 4.2.9 on 2024-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_color_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=100, verbose_name='Цвет'),
        ),
    ]
